### ISSUE TITLE
关系数据库中的范式 | CS-Tao · Blog

### ISSUE THREAD

**Issue by GIS-Hacker** [GIS-Hacker/CS-Tao.github.io-comments#39]
https://home.cs-tao.cc/blog/技术相关/关系数据库中的范式/

**Comment by HaoKunT** [comment]
## BCNF
实际生产生活中BCNF已经基本足够使用，用来进行范式分解的目的是为了保证下面几点

1. 插入能插的进去，不能说因为主键未定等原因导致插不进去，例如不满足2NF的一些表
2. 删除不丢失信息，这一点上外键起了很大的作用，例如某个院系没有学生了，但是这个院系的建制还在，不能因删除学生信息而导致这个院系的信息被一并删除
